CREATE TABLE "TRAIN" (
"id"  SERIAL ,
"Capacity" SMALLINT NOT NULL DEFAULT 100 ,
"LastStation" INTEGER NOT NULL ,
"NumOnboard" INTEGER NOT NULL DEFAULT 0 ,
PRIMARY KEY ("id")
);

CREATE TABLE "STATION" (
"id" INTEGER NOT NULL ,
"Name" VARCHAR(50) NOT NULL ,
PRIMARY KEY ("id")
);

CREATE TABLE "PASSENGER" (
"id"  SERIAL ,
"FirstName" VARCHAR(50) ,
"LastName" VARCHAR(50) ,
PRIMARY KEY ("id")
);

CREATE TABLE "STATION_AND_TRAIN" (
"Arrived" TIMESTAMP NOT NULL ,
"Departed" TIMESTAMP NOT NULL ,
"STATION.id" INTEGER NOT NULL ,
"TRAIN.id" INTEGER 
);

CREATE TABLE "TRAIN_AND_PASSENGER" (
"TRAIN.id" INTEGER ,
"PASSENGER.id" INTEGER ,
"OnboardTime" TIMESTAMP NOT NULL ,
"OffboardTime" TIMESTAMP
);

CREATE TABLE "STATION_AND_PASSENGER" (
"id"  SERIAL ,
"STATION.id" INTEGER NOT NULL ,
"PASSENGER.id" INTEGER ,
PRIMARY KEY ("id")
);

CREATE TABLE "TICKET" (
"id"  SERIAL ,
"PurchaseDate" TIMESTAMP NOT NULL ,
"UseDate" TIMESTAMP NOT NULL ,
"STATION.id" INTEGER NOT NULL ,
"PASSENGER.id" INTEGER ,
PRIMARY KEY ("id")
);

ALTER TABLE "TRAIN" ADD FOREIGN KEY ("LastStation") REFERENCES "STATION" ("id");
ALTER TABLE "STATION_AND_TRAIN" ADD FOREIGN KEY ("STATION.id") REFERENCES "STATION" ("id");
ALTER TABLE "STATION_AND_TRAIN" ADD FOREIGN KEY ("TRAIN.id") REFERENCES "TRAIN" ("id");
ALTER TABLE "TRAIN_AND_PASSENGER" ADD FOREIGN KEY ("TRAIN.id") REFERENCES "TRAIN" ("id");
ALTER TABLE "TRAIN_AND_PASSENGER" ADD FOREIGN KEY ("PASSENGER.id") REFERENCES "PASSENGER" ("id");
ALTER TABLE "STATION_AND_PASSENGER" ADD FOREIGN KEY ("STATION.id") REFERENCES "STATION" ("id");
ALTER TABLE "STATION_AND_PASSENGER" ADD FOREIGN KEY ("PASSENGER.id") REFERENCES "PASSENGER" ("id");
ALTER TABLE "TICKET" ADD FOREIGN KEY ("STATION.id") REFERENCES "STATION" ("id");
ALTER TABLE "TICKET" ADD FOREIGN KEY ("PASSENGER.id") REFERENCES "PASSENGER" ("id");
